from typing import Any, Awaitable, Callable, Protocol


class SonicWSAdapter(Protocol):
    """Cross-process room membership and broadcast contract."""

    def start(self, server_id: str, receiver: Callable[[dict[str, Any]], Awaitable[None]]): ...
    def publish(self, message: dict[str, Any]): ...
    def join(self, connection_id: int, room: str): ...
    def leave(self, connection_id: int, room: str): ...
    def disconnect(self, connection_id: int): ...
    def close(self): ...
